server:
  port: 8080

spring:
  application:
    name: api-gateway

  config:
    import: 'optional:configserver:http://CONFIG-SERVER'


  zipkin:
    base-url: 'http://localhost:9411'


management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'